[package]
name = "supermarket_jumbo"

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
reqwest.workspace = true
supermarket = { path = "../supermarket" }
tokio.workspace = true
